---
# tasks file for apache

- name: Installation de epel-release
  yum:
    name: epel-release
    state: present

- name: installation apache et  php pour OS Debian (last version)
  apt:
    name: ['apache2', 'php', 'php-mysql']
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: installation extra packages (OS Famille Debian)
  apt:
    name: "{{ extra_packages_debian }}"
    state: present
  when: ansible_facts['os_family'] == "Debian" and extra_packages_debian is defined

- name: Installation apache and php pour OS Famille Redhat (last version)
  yum:
    name: ['httpd', 'php', 'php-mysqlnd']
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"
 
- name: installation extra packages (OS Fammile RedHat)
  yum:
    name: "{{ extra_packages_redhat }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat" and extra_packages_redhat is defined

- name: Changement de droits du dossier /www/var/html
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
    recurse: yes

- name: remove default index.html
  file:
    path: /var/www/html/index.html
    state: absent


- name: Copie de la source de app-salaire
  copy:
    src: app/
    dest: /var/www/html/

- name: Deploiement de la configuration de la base de données
  template:
    src: "db-config.php.j2"
    dest: "/var/www/html/db-config.php"

- name: Confirmation du demarrage du service apache (OS Famille Debian)
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Confirmation du demarrage du service apache (OS Famille RedHat)
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"
  
- name: Ajout du service Apache au pare-feu
#  systemd:
#   name: firewalld
#   enabled: no
#   state: restarted
  firewalld:
   service: http
   permanent: true
   immediate: yes
   state: enabled
